require("mason").setup({
    PATH = "append",
    ui = {
        border = "rounded",
        backdrop = 100,
        height = 0.8,
        icons = {
            package_installed = "✓",
            package_pending = "➜",
            package_uninstalled = "✗",
        },
    },
})
require("mason-tool-installer").setup({
    ensure_installed = {
        "actionlint",
        "ansible-language-server",
        "autotools-language-server",
        "bash-language-server",
        "codelldb",
        "esbonio",
        "gitlab-ci-ls",
        "gopls",
        "harper-ls",
        "helm-ls",
        "jdtls",
        "jq",
        "json-lsp",
        "just-lsp",
        "kube-linter",
        "lemminx",
        "lua-language-server",
        "markdownlint",
        "marksman",
        "nginx-config-formatter",
        "nginx-language-server",
        "prettier",
        "ruby-lsp",
        "rubyfmt",
        "ruff",
        "rust-analyzer",
        "shellcheck",
        "shfmt",
        "sonarlint-language-server",
        "sqruff",
        "stylua",
        "taplo",
        "terraform-ls",
        "tflint",
        "tfsec",
        "trivy",
        "ty",
        "typescript-language-server",
        "xmlformatter",
        "yaml-language-server",
        "yamllint",
        "yq",
    },
    auto_update = true,
    run_on_start = true,
})
