require("mason").setup({
    PATH = "append",
    registries = {
        "file:~/.config/nvim/files/mason",
        "github:mason-org/mason-registry",
    },
    ui = {
        border = "none",
        height = 0.8,
        icons = {
            package_installed = "✓",
            package_pending = "➜",
            package_uninstalled = "✗",
        },
    },
})
require("mason-tool-installer").setup({
    ensure_installed = {
        "actionlint",
        "ansible-language-server",
        "bash-language-server",
        "checkmake",
        "esbonio",
        "gitlab-ci-ls",
        "gopls",
        "helm-ls",
        "jq",
        "json-lsp",
        "lemminx",
        "lua-language-server",
        "markdownlint",
        "marksman",
        "mypy",
        "prettier",
        "pyright",
        "ruff",
        "rust-analyzer",
        "shellcheck",
        "shfmt",
        "sonarlint-language-server",
        "sqruff",
        "stylua",
        "taplo",
        "terraform-ls",
        "tflint",
        "tfsec",
        "typescript-language-server",
        "xmlformatter",
        "yaml-language-server",
        "yamllint",
        "yq",
    },
    auto_update = true,
    run_on_start = true,
})
