require("mason").setup({
	ui = {
        border = "rounded",
        height = 0.8,
		icons = {
			package_installed = "✓",
			package_pending = "➜",
			package_uninstalled = "✗",
		},
	},
})
require("mason-tool-installer").setup({
	ensure_installed = {
		"ansible-language-server",
		"ansible-lint",
		"autopep8",
		"bash-language-server",
		"black",
		"esbonio",
		"flake8",
		"glow",
		"gopls",
		"helm-ls",
		"jq",
		"json-lsp",
		"lua-language-server",
		"ltex-ls",
		"markdownlint",
		"prettier",
		"pyright",
		"shellcheck",
		"shfmt",
		"sonarlint-language-server",
		"stylua",
		"taplo",
		"terraform-ls",
		"tflint",
		"tfsec",
		"typescript-language-server",
		"yaml-language-server",
		"yamllint",
		"yq",
		"actionlint",
	},
	auto_update = true,
	run_on_start = true,
})
