require("nvim-treesitter").install({
	"awk",
	"bash",
	"c",
	"cmake",
	"comment",
	"csv",
	"diff",
	"dockerfile",
	"go",
	"graphql",
	"groovy",
	"hcl",
	"html",
	"http",
	"ini",
	"java",
	"javascript",
	"jinja",
	"jq",
	"json",
	"json5",
	"jsonc",
	"just",
	"lua",
	"luadoc",
	"make",
	"markdown",
	"markdown_inline",
	"perl",
	"python",
	"regex",
	"requirements",
	"rst",
	"ruby",
	"sql",
	"swift",
	"terraform",
	"toml",
	"typescript",
	"vim",
	"vimdoc",
	"xml",
	"yaml",
	"ghactions",
})

require("ts_context_commentstring").setup({})
local get_option = vim.filetype.get_option
vim.filetype.get_option = function(filetype, option)
	return option == "commentstring" and require("ts_context_commentstring.internal").calculate_commentstring()
		or get_option(filetype, option)
end
