require("settings.vim")
require("settings.autocmd")
require("settings.neovide")
require("settings.rustaceanvim")
require("settings.keymaps")
require("settings.commands")
require("settings.filetypes")
require("settings.lsp")
pcall(require, "settings.private.mac")
