dialect = "uk"
auto_sync = false
update_check = false
search_mode = "fuzzy"
invert = true
show_preview = true
show_help = false
enter_accept = true
style = "compact"
prefers_reduced_motion = true
workspaces = true
ctrl_n_shortcuts = false

[theme]
name = "catppuccin-mocha"
