palette = "catppuccin_mocha"
add_newline = false
# format = """$directory$character${custom.incognito}"""
# right_format = """$kubernetes"""
# format = """$kubernetes $git_branch${custom.mise}\n$directory${custom.character}${custom.incognito}"""
format = """$aws$gcloud$azure$kubernetes$git_branch${custom.mise}\n$directory${character}"""
continuation_prompt = "[❯](blue) "

[character]
success_symbol = "[❯](red)[❯](yellow)[❯](green)"
error_symbol = "[❯](red)[❯](yellow)[❯](green)"

[directory]
style = "text"
truncation_symbol = ""

# [custom.character]
# format = "[❯](red)[❯](yellow)[❯](green) "
# shell = 'bash'
# when = '[ -n "${HISTFILE}" ]'

[custom.incognito]
format = "[❯](text)[❯](text)[❯](text) "
shell = 'bash'
when = '[ -z "${HISTFILE}" ]'

[custom.mise]
symbol = "⍟ "
format = "[$symbol$output]($style)"
command = "mise current | xargs"
detect_files = [".mise.toml"]
style = "green"

# [custom.github]
# symbol = "⍟ "
# format = "[$symbol$output]($style)"
# command = "${HOME}/.local/bin/get-active-gh-user.sh"
# detect_files = [".mise.toml"]
# style = "green"

[git_branch]
symbol = "⑆ "
format = '[$symbol$branch]($style) '
style = 'peach'

[git_status]
format = '$all_status$ahead_behind'
ahead = '[⬆](bold purple) '
behind = '[⬇](bold purple) '
staged = '[✚](green) '
deleted = '[✖](red) '
renamed = '[➜](purple) '
stashed = '[✭](cyan) '
untracked = '[◼](white) '
modified = '[✱](blue) '
conflicted = '[═](yellow) '
diverged = '⇕ '
up_to_date = ''

[cmd_duration]
disabled = true

[line_break]
disabled = true

[status]
disabled = true

[package]
disabled = true

[helm]
disabled = true

[kubernetes]
disabled = false
symbol = ""
format = "[$symbol $context()]($style) "
style = "red"

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
style = "yellow"
symbol = " "

[azure]
symbol = "󰠅 "
format = "[$symbol($subscription)]($style) "
style = "blue"
disabled = false

[gcloud]
symbol = "󱇶 "
format = '[$symbol$account(@$domain)(\($region\))]($style) '
style = "green"
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
