require("trouble").setup({
    icons = {
        folder_closed = "📁",
        folder_open = "📂",
        kinds = {
            Array = "[Array]",
            Boolean = "[Boolean]",
            Class = "[Class]",
            Constant = "[Constant]",
            Constructor = "[Constructor]",
            Enum = "[Enum]",
            EnumMember = "[EnumMember]",
            Event = "[Even]",
            Field = "[FileId]",
            File = "[File]",
            Function = "[Function]",
            Interface = "[Interface]",
            Key = "[Key]",
            Method = "[Method]",
            Module = "[Module]",
            Namespace = "[Namespace]",
            Null = "[Null]",
            Number = "[Number]",
            Object = "[Object]",
            Operator = "[Operator]",
            Package = "[Package]",
            Property = "[Property]",
            String = "[String]",
            Struct = "[Struct]",
            TypeParameter = "[TypeParameter]",
            Variable = "[Variable]",
        },
    },
    indent_lines = false,
    signs = {
        error = "error",
        warning = "warn",
        hint = "hint",
        information = "info",
    },
})
