[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#7F849C"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#cdd6f4"
background = "#181825"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

[cursor]
style = { shape = "Block"}
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "SFMono Nerd Font Mono"
# family = "SF Mono"
style = "Bold"

[font.italic]
family = "SFMono Nerd Font Mono"
# family = "SF Mono"
style = "Italic"

[font.normal]
family = "SFMono Nerd Font Mono"
# family = "SF Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0001\u0001"
key = "Left"
mods = "super"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "super"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

# Unbind new tab creation
[[keyboard.bindings]]
action = "None"
key = "T"
mods = "Command"

[scrolling]
multiplier = 0

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
mouse.enabled = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[window]
blur = true
decorations = "buttonless"
dynamic_padding = false
# opacity = 0.85
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5
