default_profile = "default"
[profiles.default]
adapter = "sqlite"
theme = "catppuccin-mocha"
limit = 100000
keymap_name = ["vscode"]
[profiles.test]
adapter = "sqlite"
theme = "catppuccin-mocha"
limit = 100000
keymap_name = ["vscode"]
